### PR TITLE
Use createrepo_c instead of createrepo

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
Sure no problem. This is why I handled this case in qubes-builder PR.

**Comment by marmarek** [comment]
Shellcheck complains.

**Comment by fepitre** [comment]
Ok will change it. I just copy pasted your referenced code.

**Comment by marmarek** [comment]
I know shellcheck complained, but `command -v` doesn't work on Debian (sh=dash). It checks the command, but doesn't print them. See travis log.

**Comment by fepitre** [comment]
So finally I drop the commit?

**Comment by marmarek** [comment]
Not this one, change to previous version using `which`. And add a comment to ignore this particular shellcheck check.

**Pull request merged**
