### PR TITLE
Better shell quoting

### PR DESCRIPTION
**Pull request by DemiMarie**
Mostly adding double quotes

### CODE REVIEW

**Comment by marmarek** [comment]
Maybe we want shellcheck plugged into CI here? Like we have in core-agent-linux.

**Comment by DemiMarie** [comment]
We almost certainly do; shell is like perl but without `use strict;` as an option.

**Comment by fepitre** [comment]
> Maybe we want shellcheck plugged into CI here? Like we have in core-agent-linux.

Yes I agree. For example, even if on each PR we try to make shellcheck happy on every modified script, It would be better to have an explicit check list on files to be linted.

**Comment by fepitre** [comment]
I've added it here: https://github.com/QubesOS/qubes-builder-rpm/pull/86. Feel free to cherry-pick those commits or Marek to merge first the branch with shellcheck and retry here.

**Comment by marmarek** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]

**Pull request merged**
