### PR TITLE
Fc29

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by marmarek** [comment]
Have you managed to build all the packages? For me xen build fails:
```
sudo BACKEND_VMM=xen  chroot /home/user/builder-R4.0-templates/chroot-fc29 sh -c 'cd /home/user/qubes-src/vmm-xen; dnf builddep --allowerasing --best  -y xen.spec'
Qubes OS Builder Repository                     2.8 MB/s | 2.9 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Sun 02 Sep 2018 12:30:12 PM UTC.
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
sh: /usr/bin/python: No such file or directory
Package gettext-0.19.8.1-17.fc29.x86_64 is already installed, skipping.
Package perl-podlators-1:4.11-3.fc29.noarch is already installed, skipping.
Package perl-podlators-1:4.11-3.fc29.noarch is already installed, skipping.
Package systemd-239-3.fc29.x86_64 is already installed, skipping.
Package systemd-udev-239-3.fc29.x86_64 is already installed, skipping.
Error: 
 Problem: package glibc-devel-2.28-9.fc29.i686 requires glibc-headers = 2.28-9.fc29, but none of the providers can be installed
  - cannot install both glibc-headers-2.28-6.fc29.x86_64 and glibc-headers-2.28-9.fc29.x86_64
  - glibc-headers-2.28-6.fc29.i686 has inferior architecture
  - package libxcrypt-devel-4.1.2-1.fc29.i686 requires glibc-headers(x86-32) >= 2.26.9000-46, but none of the providers can be installed
  - package glibc-devel-2.28-9.fc29.i686 requires libxcrypt-devel(x86-32) >= 4.0.0, but none of the providers can be installed
  - cannot install the best candidate for the job
make[2]: *** [/home/user/builder-R4.0-templates/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:57: dist-build-dep] Error 1
make[1]: *** [Makefile.generic:177: packages] Error 1
make: *** [Makefile:217: vmm-xen-vm] Error 1
```

**Comment by marmarek** [comment]
With `RPM_USE_MOCKBUILD` build deps step suceeded, but failed on missing `python`, there was also complain about missing `hostname` tool.

**Comment by fepitre** [comment]
Yes I succeeded to build all packages and template (currently using it) two weeks ago. I will check whats wrong.

**Comment by fepitre** [comment]
FYI i did not used mock

**Comment by marmarek** [comment]
I get this by doing fresh qubes-builder clone, with `example-configs/qubes-os-r4.0.conf` (and commenting out pvgrub, because of a network problem on get-sources).

**Comment by fepitre** [comment]
Oh, you are notre using my branch xen-4.11-devel based on your branch?

**Comment by marmarek** [comment]
No, xen-4.8. Some BuildRequires needs to be updated (at least for non-mock case)?

**Comment by fepitre** [comment]
Oh yes probably. I only built xen-4.11 (same as in Fedora 29)

**Comment by marmarek** [comment]
I'm going to merge this one, as problem looks to be in vmm-xen, not here. But please take a look at it, it is a blocker for fc29 template for R4.0.

**Comment by fepitre** [comment]
I now got also this problem with xen-4.11-devel branch. It seems to be a problem with rpm resolution for dependencies. I will dig into the problem.

**Pull request merged**
