### PR TITLE
Reproducible legacy builds; softcode $giturl for @CHANGELOG@

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by marmarek** [comment]
Any specific reason for this? We're phasing out legacy builds for release packages (all qubes-builder instances for R4.1 have already `USE_DIST_BUILD_TOOLS=1`).

Not that I'm against this change, it is fine.

**Comment by rustybird** [comment]
> Any specific reason for this?

Just that `USE_DIST_BUILD_TOOLS=1` isn't set in qubes-contrib-configs. Should it be?

**Comment by marmarek** [comment]
Yes, it should.
cc @fepitre

**Comment by fepitre** [comment]
@rustybird : I've added the option. Thank you for the report and your last PR on configs too.

**Comment by marmarek** [comment]
@fepitre centos7 tests fails (see travis logs), unrelated to this PR. Please either fix, or remove them.

**Pull request merged**
